### ISSUE TITLE
service启动不成功 “return (connectionString.startsWith('mongodb://')”

### ISSUE THREAD

**Issue by a1076857838** [luckywangxi/chatgpt-web-1#1]
![微信截图_20230328144535](https://user-images.githubusercontent.com/82078282/228152257-d7a38225-18b6-46bf-af54-c46b32ca945b.png)
出现这个情况，不知道是不是mongodb数据库的问题，没用过这个数据库，按照百度安装了这个数据库之后，还是启动不起来

**Comment by luckywangxi** [comment]
> ![微信截图_20230328144535](https://user-images.githubusercontent.com/82078282/228152257-d7a38225-18b6-46bf-af54-c46b32ca945b.png) 出现这个情况，不知道是不是mongodb数据库的问题，没用过这个数据库，按照百度安装了这个数据库之后，还是启动不起来

我看一下你的docker compose文件

**Comment by a1076857838** [comment]
原来本地启动docker compose也需要改动啊，我没改这个文件0.0
我去研究一下

**Comment by kkxs888** [comment]
有演示网页吗，去观摩下大佬的作品

**Comment by luckywangxi** [comment]
thew.top

**Comment by luckywangxi** [comment]
> thew.top
> 

自用的
